# GitHub Actions workflow for Development environment
# Triggers on push to development branch

name: Development CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  NODE_ENV: development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linter
        run: npm run lint || echo "Linter not configured"
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build || echo "Build not required"

  # Add deployment job here when ready
