AWSTemplateFormatVersion: '2010-09-09'
Description: 'DevHub API Production Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - certification
      - production

Resources:
  # VPC Configuration
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub devhub-${Environment}-vpc

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub devhub-api-${Environment}
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  # Add more resources as needed
